### PR TITLE
support for lancedb as vectordb

### PR DESCRIPTION
**Pull request by akashAD98**
added  support for lancedb

### CODE REVIEW

**Comment by SimFG** [comment]
please set the target branch to the dev branch, and fix the lint error

**Comment by akashAD98** [comment]
@SimFG

**Comment by akashAD98** [comment]
@SimFG can you please help me in this pr? your help would be appreciated thanks.

**Comment by SimFG** [comment]
@akashAD98 got it, i will check it

**Comment by SimFG** [comment]
you can try to execute `make pylint_check` to find the lint error

**Comment by akashAD98** [comment]
> you can try to execute `make pylint_check` to find the lint error

yes actually I used it still not sure why its missing even I did respective changes

**Pull request merged**
