### PR TITLE
[add] support for mongodb storage

### PR DESCRIPTION
**Pull request by a9raag**
Support for MongoDB storage.
ORM used for MongoDB: mongo-engine 
_Design is modeled after sql_storage.py for consistency_

### CODE REVIEW

**Comment by SimFG** [comment]
Thanks your contribution!

**Comment by SimFG** [comment]
@a9raag please make the dev branch as the target branch

**Comment by a9raag** [comment]
> @a9raag please make the dev branch as the target branch

Done

**Pull request merged**
