### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by junjiejiangjjj**

### CODE REVIEW

**Comment by SimFG** [comment]
Found a small problem, if the directory does not exist, it will not be created automatically, the user needs to create it manually, otherwise an error will be reported

**Comment by junjiejiangjjj** [comment]
> Found a small problem, if the directory does not exist, it will not be created automatically, the user needs to create it manually, otherwise an error will be reported

fixed in this pr.

**Comment by SimFG** [comment]
image

**Comment by junjiejiangjjj** [comment]
> image

fixed

**Pull request merged**
