### PR TITLE
added support for weaviate vector databse

### PR DESCRIPTION
**Pull request by pranaychandekar**

### CODE REVIEW

**Comment by pranaychandekar** [comment]
@cxie @SimFG All the methods of Weaviate vector class in weaviate.py is tested with a dev installation inside a docker container. They are working as expected. Eager to get this released as soon as possible.

**Comment by pranaychandekar** [comment]
Hi @SimFG 

Thanks for merging this. Assuming that this would come in next release, when can we expect the next release?

**Comment by SimFG** [comment]
@pranaychandekar maybe tomorrow 😆

**Comment by pranaychandekar** [comment]
Thanks a lot @SimFG . Team GPTCache is awesome!

**Comment by pranaychandekar** [comment]
@hsm207 Now we have what you requested for in #340

**Comment by SimFG** [comment]
@pranaychandekar the weaviate unit test can't work. if you have a free time, please help to fix it

**Pull request merged**
