### PR TITLE
support paddlenlp embedding

### PR DESCRIPTION
**Pull request by vax521**
support paddlenlp embedding for issue #281

### CODE REVIEW

**Comment by SimFG** [comment]
@vax521 thanks your contribution!!! And you need to add some test cases about new embedding function.

**Comment by SimFG** [comment]
@vax521 in the test case, can you give a small model, because the large model will cause the long test time

**Comment by vax521** [comment]
> @vax521 in the test case, can you give a small model, because the large model will cause the long test time

OK

**Comment by SimFG** [comment]
@vax521 the pr is ok, please check the unit test failure.

**Comment by SimFG** [comment]
Thanks your patience. Can you combine all commits into one? you can use the `git rebase`, and than `git push -f`

**Pull request closed without merging**
