### PR TITLE
Add UForm multi-modal embeddings generator

### PR DESCRIPTION
**Pull request by ashvardanian**
Hey, I'd like to add Unum's [UForm](https://github.com/unum-cloud/uform) as a CLIP-like multi-modal embedding generator.

LMK if I should change/add something.

Thanks!

### CODE REVIEW

**Comment by SimFG** [comment]
Thanks a lot your contribution!!! And the target branch should be dev

**Comment by ashvardanian** [comment]
Sure, fixed :)

**Comment by SimFG** [comment]
@ashvardanian please rebase the latest dev branch

**Comment by ashvardanian** [comment]
Done, @SimFG

**Comment by SimFG** [comment]
@ashvardanian please add a simple test case, which can use the mock server, like the openai test case

**Comment by SimFG** [comment]
@ashvardanian i will close the pull request and change some code for the unit test case passport

**Pull request closed without merging**
