### PR TITLE
Fix when partition key is not supplied

### PR DESCRIPTION
**Pull request by ziyi-curiousthing**
Fix when partition key is not supplied, default to empty string.

### CODE REVIEW

**Comment by SimFG** [comment]
@ziyi-curiousthing it doesn't seem to change obviously. When partition_key is what value, an exception will occur

**Comment by ziyi-curiousthing** [comment]
@SimFG This is to fix the case where user doesn't supply partition_key, so it is passed in as `None` and Milvus doesn't like it because the field type is string. I am not quite sure how to set the field to be optional so that it can take None (or save without this property). Any suggestions?

**Comment by SimFG** [comment]
@ziyi-curiousthing maybe when the partition key is None, you can set it's value to `default`, like:
```
partition_key = kwargs.get("partition_key", "default")
```

**Comment by SimFG** [comment]
And for the better way, you should have a param when  initing the milvus, which is whether enable the partition key function.

**Comment by ziyi-curiousthing** [comment]
> And for the better way, you should have a param when initing the milvus, which is whether enable the partition key function.

Thank you @SimFG for your feedback. Should be addressed now.

**Pull request merged**
